osx_image: xcode9
language: objective-c
branches:
  only:
    - master
before_install:
    - gem install xcpretty
before_script:
    - set -o pipefail
script:
    - xcodebuild test -project ./simple-tween.xcodeproj -scheme simple-tweenTests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 7' | xcpretty -c
